/*
 * File: app/view/UserModuleViewController.js
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MovieApp.view.MovieModuleViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mrmoviemodule',

    show : function() {
        "use strict";

        var me = this;
        me.getView().show();

        var context = me.setupContext();
        context.data.load();
    },

    setupContext: function() {  
        var me = this,
            win = me.getView();

        win.context = Ext.create('iRely.Engine', {
            window : win,
            store  : Ext.create('MovieApp.store.MovieModuleStore'),
            singleGridMgr: Ext.create('iRely.grid.Manager', {
                grid:  win.down('grid'),
                title: 'Movie Screen',
                columns: [
                    
                    {
                        xtype: 'gridcolumn',
                        itemId: 'colMovieName',
                        dataType: 'string',
                        dataIndex: 'strMovieName',
                        flex: 1,
                        text: 'Movie Title',
                        editor: {
                            xtype: 'textfield',
                            name: 'strMovieName'
                        }
                    },
                    {
                        xtype: 'gridcolumn',
                        itemId: 'colGenre',
                        dataType: 'string',
                        dataIndex: 'strGenre',
                        flex: 1,
                        text: 'Genre',
                        editor: {
                            xtype: 'combobox',
                            name: 'strGenre',
                            store: ['Action', 'Romance', 'Anime', 'Horror', 'Sci-Fi', 'Drama'],
                            queryMode: 'local',
                        }
                    },
                    {
                        xtype: 'gridcolumn',
                        itemId: 'colDirector',
                        dataType: 'string',
                        dataIndex: 'strDirector',
                        flex: 1,
                        text: 'Director',
                        editor: {
                            xtype: 'textfield',
                            name: 'strDirector'
                        }
                    },
                    {
                        xtype: 'gridcolumn',
                        itemId: 'colPrice',
                        dataType: 'float',
                        dataIndex: 'dblPrice',
                        flex: 1,
                        text: 'Price',
                        editor: {
                            xtype: 'textfield',
                            name: 'dblPrice'
                        }
                    }
                ]
            })
        }); 
    return win.context;
    }

});
