/*
 * File: app/view/TransactionItem.js
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MovieApp.view.TransactionItem', {
    extend: 'Ext.window.Window',
    alias: 'widget.mrtransactionitem',

    requires: [
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Boolean',
        'Ext.grid.column.Date',
        'Ext.view.Table',
        'Ext.grid.plugin.CellEditing'
    ],

    height: 570,
    width: 799,
    layout: 'fit',
    title: 'Rentals',

    items: [
        {
            xtype: 'form',
            ui: 'i21-form',
            bodyPadding: 10,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'top',
                    ui: 'i21-toolbar',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnNew',
                            ui: 'i21-button-toolbar-small',
                            text: 'New'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSave',
                            ui: 'i21-button-toolbar-small',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnFind',
                            ui: 'i21-button-toolbar-small',
                            text: 'Find'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnDelete',
                            ui: 'i21-button-toolbar-small',
                            text: 'Delete'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnClose',
                            ui: 'i21-button-toolbar-small',
                            text: 'Close'
                        }
                    ]
                },
                {
                    xtype: 'ipagingstatusbar',
                    flex: 1,
                    dock: 'bottom'
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    bodyCls: 'i21-tab',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Details',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    itemId: 'ctnHeader',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'gridcombobox',
                                                    columns: [
                                                        {
                                                            dataIndex: 'intUserId',
                                                            dataType: 'int',
                                                            text: 'Customer ID',
                                                            hidden: true
                                                        },
                                                        {
                                                            dataIndex: 'strName',
                                                            dataType: 'string',
                                                            text: 'Customer Name',
                                                            flex: 1
                                                        }
                                                    ],
                                                    flex: 1,
                                                    itemId: 'cboCustomerName',
                                                    margin: '5 10 10 5',
                                                    fieldLabel: 'Customer Name',
                                                    displayField: 'strName',
                                                    valueField: 'strName',
                                                    enableDrillDown: true
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'datefield',
                                            flex: 1,
                                            itemId: 'dtmRentDate',
                                            margin: '5 10 10 5',
                                            fieldLabel: 'Rent Date'
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                        {
                                            xtype: 'gridcombobox',
                                            columns: [                                                
                                                {
                                                    dataIndex: 'strStatus',
                                                    dataType: 'string',
                                                    text: 'Transaction Status',
                                                    flex: 1
                                                }
                                            ],
                                            flex: 1,
                                            itemId: 'cboStatus',
                                            margin: '5 10 10 5',
                                            fieldLabel: 'Status',
                                            displayField: 'strStatus',
                                            valueField: 'strStatus',
                                            listConfig: {
                                                maxHeight: 150, 
                                                width: 200 
                                            }
                                        
                                    }
                                ]
                            },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            itemId: 'txtRentId',
                                            margin: '5 10 10 5',
                                            fieldLabel: 'Transaction ID',
                                            readOnly: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 2,
                                    itemId: 'ctnDetails',
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'frmadvancesearchgrid',
                                            flex: 1,
                                            itemId: 'gridRentDetails',
                                            title: 'Rented Movies',
                                            dockedItems: [
                                                {
                                                xtype: 'toolbar',
                                                dock: 'top',
                                                componentCls: 'i21-toolbar-grid',
                                                itemId: 'tblGridOptions',
                                                items: [                                                 
                                                    {
                                                        xtype: 'button',
                                                        itemId: 'btnRemove',
                                                        iconCls: 'small-remove',
                                                        text: 'Delete'
                                                    }                                                    
                                                ]
                                            }
                                        ],
                
                                            columns: [                                                
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    itemId: 'colMovieTitle',
                                                    dataIndex: 'string',
                                                    text: 'Title',                                       
                                                    editor: {
                                                        xtype: 'gridcombobox',  
                                                        columns: [
                                                            {
                                                                dataIndex: 'intMovieId',
                                                                dataType: 'int',
                                                                text: 'Movie ID',
                                                                hidden: true
                                                            },
                                                            {
                                                                dataIndex: 'strMovieName',
                                                                dataType: 'string',
                                                                text: 'Movie Name',
                                                                flex: 1
                                                            }
                                                        ],                                                             
                                                        displayField: 'strMovieName',
                                                        valueField: 'strMovieName',
                                                        listConfig: {
                                                            maxHeight: 150, 
                                                            width: 300
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    flex: 1,
                                                    itemId: 'colReturnDate',
                                                    dataIndex: 'date',
                                                    text: 'Return Date',
                                                    editor: {
                                                        xtype: 'datefield'
                                                    }
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    itemId: 'colStatus',
                                                    dataIndex: 'string',
                                                    text: 'Movie Status',
                                                    editor: {
                                                        xtype: 'gridcombobox',
                                                        columns: [
                                                            {
                                                                dataIndex: 'strStatus',
                                                                dataType: 'string',
                                                                text: 'Status',
                                                                flex: 1
                                                            }
                                                        ],
                                                        displayField: 'strStatus',
                                                        valueField: 'strStatus',
                                                        listConfig: {
                                                            maxHeight: 150, 
                                                            width: 200 
                                                        }
                                                    }
                                                },
                                               
                                            ],
                                            plugins: [
                                                {
                                                    ptype: 'cellediting',
                                                    clicksToEdit: 1
                                                }
                                            ],
                                            selModel: {
                                                selType: 'checkboxmodel'
                                            }
                                        }
                                    ]
                                }
                            ]
                            
                        },
                        {
                            xtpye: 'panel',
                            itemId: 'pnlAuditLog',
                            layout: 'fit',
                            title: 'Audit Log',
                            items: [
                                {
                                    xtype: 'auditlogtree'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});