/*
 * File: app/view/UserModuleViewController.js
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MovieApp.view.TransactionModuleViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mrtransactionmodule',

    show : function() {
        "use strict";

        var me = this;
        me.getView().show();

        var context = me.setupContext();
        context.data.load();
    },

    setupContext: function() {  
        var me = this,
            win = me.getView();

        win.context = Ext.create('iRely.Engine', {
            window : win,
            store  : Ext.create('MovieApp.store.TransactionModuleStore'),
            singleGridMgr: Ext.create('iRely.grid.Manager', {
                grid:  win.down('grid'),
                title: 'Transaction Screen',
                columns: [
                    
                    {
                        xtype: 'gridcolumn',
                        itemId: 'colUserId',
                        dataType: 'int',
                        dataIndex: 'intUserId',
                        flex: 1,
                        text: 'User Id',
                        editor:{
                            xtype: 'textfield',
                            name: 'intUserId'                            
                          },
                    },                    
                    {
                        xtype: 'datecolumn',
                        itemId: 'colRentDate',
                        dataType: 'date',
                        dataIndex: 'dtmRentDate',
                        flex: 1,
                        text: 'Rent Date',
                        editor: {
                            xtype: 'datefield',
                            name: 'dtmRentDate',                           
                            
                        }
                    }
                ]
            })
        }); 
    return win.context;
    }

});
