/*
 * File: app/view/UserModuleViewController.js
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MovieApp.view.UserModuleViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mrusermodule',

    show : function() {
        "use strict";

        var me = this;
        me.getView().show();

        var context = me.setupContext();
        context.data.load();
    },

    setupContext: function() {  
        var me = this,
            win = me.getView();

        win.context = Ext.create('iRely.Engine', {
            window : win,
            store  : Ext.create('MovieApp.store.UserModuleStore'),
            singleGridMgr: Ext.create('iRely.grid.Manager', {
                grid:  win.down('grid'),
                title: 'User Screen',
                columns: [
                    
                    {
                        xtype: 'gridcolumn',
                        itemId: 'colName',
                        dataType: 'string',
                        dataIndex: 'strName',
                        flex: 1,
                        text: 'Name',
                        editor: {
                            xtype: 'textfield',
                            name: 'strName'
                        }
                    },
                    {
                        xtype: 'gridcolumn',
                        itemId: 'colGender',
                        dataType: 'string',
                        dataIndex: 'strGender',
                        flex: 1,
                        text: 'Gender',
                        editor: {
                            xtype: 'combobox',
                            name: 'strGender',
                            store: ['Female', 'Male', 'Asexual'],
                            queryMode: 'local',
                        }
                    },
                    {
                        xtype: 'datecolumn',
                        itemId: 'colBirthdate',
                        dataType: 'date',
                        dataIndex: 'dtmBirthdate',
                        flex: 1,
                        text: 'Birthdate',
                        editor: {
                            xtype: 'datefield',
                            name: 'dtmBirthdate',                           
                            
                        }
                    },
                    {
                        xtype: 'gridcolumn',
                        itemId: 'colAddress',
                        dataType: 'string',
                        dataIndex: 'strAddress',
                        flex: 1,
                        text: 'Address',
                        editor: {
                            xtype: 'textfield',
                            name: 'strAddress'
                        }
                    },
                    {
                        xtype: 'gridcolumn',
                        itemId: 'colEmail',
                        dataType: 'string',
                        dataIndex: 'strEmail',
                        flex: 1,
                        text: 'Email',
                        editor: {
                            xtype: 'textfield',
                            name: 'strEmail'
                        }
                    },
                    {
                        xtype: 'gridcolumn',
                        itemId: 'colPhone',
                        dataType: 'string',
                        dataIndex: 'strPhone',
                        flex: 1,
                        text: 'Phone',
                        editor: {
                            xtype: 'textfield',
                            name: 'strPhone'
                        }
                    }
                ]
            })
        }); 
    return win.context;
    }

});
