/*
 * File: app/view/UserModule.js
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.7.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.7.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MovieApp.view.UserModule', {
    extend: 'GlobalComponentEngine.view.GridTemplate',
    alias: 'widget.mruser',
    
    requires: [
        'GlobalComponentEngine.view.GridTemplate',
        'MovieApp.view.UserModuleViewModel'
    ],

    viewModel: {
        type: 'usermodule'
    },
    height: 499,
    width: 524,
    title: 'User'

});